global function CRMframeworkAddSetings

void function CRMframeworkAddSetings(){
	AddModTitle("^00f5d400Custom Reticle Mod ^fee44000vmt UI Framework")
	AddModCategory("^fdffb600GLOBAL SETTINGS")
	AddConVarSettingEnum("CRM.offset_disable", "Reticle Offset Killswitch", ["[              OFF              ]", "[              ON                ]"])
	AddConVarSettingEnum("CRM.cstm_color_override", "Custom color overrides colourblind settings", ["[              OFF              ]", "[              ON                ]"])
	AddConVarSettingEnum("CRM.rgb_override", "^ff010000R^00ff0000G^0000ff00B^e0e0e000 mode", ["[              OFF              ]", "[              ON                ]"])
	AddConVarSettingSlider("CRM.offset_scalar_global","Global offset scalar", -10, 10, 1, true)
	//AddModSettingsButton("Auto calibrate Global offset scalar",
	//AddModCategory("temp!FOV Presets [type 'exec crf_fov' in console]")
	AddModCategory("^fdffb600Universal Scopes^e0e0e000 [close/mid range]")
	AddModCategory("^fdffb600HCOG2^e0e0e000 [R201;R101;HEMLOK;G2;V-47;ALTERNATOR]")
	AddConVarSetting("CRM.hcog2_base_colorR", "^ff010000Red^e0e0e000 color intensity", "float")
	AddConVarSetting("CRM.hcog2_base_colorG", "^00ff0000Green^e0e0e000 color intensity", "float")
	AddConVarSetting("CRM.hcog2_base_colorB", "^0000ff00Blue^e0e0e000 color intensity", "float")
	AddConVarSetting("CRM.hcog2_reticle_scale","Front Reticle Scale", "float")
	AddConVarSetting("CRM.hcog2_windage_scale","Rear Windage Scale", "float")
	//AddConVarSetting("CRM.hcog2_offset_scalar","Offset Strength multiplier","float")
	AddConVarSettingSlider("CRM.hcog2_reticle_style","Front reticle style [0-7]", 0, 7, 1, true)
	AddConVarSettingSlider("CRM.hcog2_windage_style","Rear windage style [0-7]", 0, 7, 1, true)
	AddModCategory("^fdffb600ACGS^e0e0e000 [UNIVERSAL]")
	AddConVarSetting("CRM.acgs_base_colorR", "^ff010000Red^e0e0e000 color intensity", "float")
	AddConVarSetting("CRM.acgs_base_colorG", "^00ff0000Green^e0e0e000 color intensity", "float")
	AddConVarSetting("CRM.acgs_base_colorB", "^0000ff00Blue^e0e0e000 color intensity", "float")
	AddConVarSetting("CRM.acgs_reticle_scale","Front Reticle Scale", "float")
	AddConVarSetting("CRM.acgs_windage_scale","Rear Windage Scale", "float")
	//AddConVarSetting("CRM.acgs_offset_scalar","Offset Strength multiplier","float")
	AddConVarSettingSlider("CRM.acgs_reticle_style","Front reticle style [0-7]", 0, 7, 1, true)
	AddConVarSettingSlider("CRM.acgs_windage_style","Rear windage style [0-7]", 0, 7, 1, true)
	AddModCategory("^fdffb600AOG_R1^e0e0e000 [R101]")
	AddConVarSetting("CRM.aog_r1_base_colorR", "^ff010000Red^e0e0e000 color intensity", "float")
	AddConVarSetting("CRM.aog_r1_base_colorG", "^00ff0000Green^e0e0e000 color intensity", "float")
	AddConVarSetting("CRM.aog_r1_base_colorB", "^0000ff00Blue^e0e0e000 color intensity", "float")
	AddConVarSetting("CRM.aog_r1_reticle_scale","Front Reticle Scale", "float")
	AddConVarSetting("CRM.aog_r1_windage_scale","Rear Windage Scale", "float")
	//AddConVarSetting("CRM.aog_r1_offset_scalar","Offset Strength multiplier","float")
	AddConVarSettingSlider("CRM.aog_r1_reticle_style","Front reticle style [0-7]", 0, 7, 1, true)
	AddConVarSettingSlider("CRM.aog_r1_windage_style","Rear windage style [0-7]", 0, 7, 1, true)
	AddModCategory("^fdffb600AOG_R2^e0e0e000 [SPITFIRE;LSTAR;DEVOTION]")
	AddConVarSetting("CRM.aog_r2_base_colorR", "^ff010000Red^e0e0e000 color intensity", "float")
	AddConVarSetting("CRM.aog_r2_base_colorG", "^00ff0000Green^e0e0e000 color intensity", "float")
	AddConVarSetting("CRM.aog_r2_base_colorB", "^0000ff00Blue^e0e0e000 color intensity", "float")
	AddConVarSetting("CRM.aog_r2_reticle_scale","Front Reticle Scale", "float")
	AddConVarSetting("CRM.aog_r2_windage_scale","Rear Windage Scale", "float")
	//AddConVarSetting("CRM.aog_r2_offset_scalar","Offset Strength multiplier","float")
	AddConVarSettingSlider("CRM.aog_r2_reticle_style","Front reticle style [0-7]", 0, 7, 1, true)
	AddConVarSettingSlider("CRM.aog_r2_windage_style","Rear windage style [0-7]", 0, 7, 1, true)
	AddModCategory("^fdffb600THREAT_SCOPE^e0e0e000 [R201;R101;HEMLOK;G2;V-47;SPITFIRE;LSTAR;DEVOTION]")
	AddConVarSetting("CRM.cro_base_colorR", "^ff010000Red^e0e0e000 color intensity", "float")
	AddConVarSetting("CRM.cro_base_colorG", "^00ff0000Green^e0e0e000 color intensity", "float")
	AddConVarSetting("CRM.cro_base_colorB", "^0000ff00Blue^e0e0e000 color intensity", "float")
	AddConVarSetting("CRM.cro_reticle_scale","Front Reticle Scale", "float")
	//AddConVarSetting("CRM.cro_offset_scalar","Offset Strength multiplier","float")
	AddConVarSettingSlider("CRM.cro_reticle_style","Front reticle style [0-7]", 0, 7, 1, true)
	AddModCategory("^fdffb600HOLO_R2^e0e0e000 [CAR;VOLT;R97]")
	AddConVarSetting("CRM.holo_r2_base_colorR", "^ff010000Red^e0e0e000 color intensity", "float")
	AddConVarSetting("CRM.holo_r2_base_colorG", "^00ff0000Green^e0e0e000 color intensity", "float")
	AddConVarSetting("CRM.holo_r2_base_colorB", "^0000ff00Blue^e0e0e000 color intensity", "float")
	AddConVarSetting("CRM.holo_r2_reticle_scale","Front Reticle Scal", "float")
	AddConVarSetting("CRM.holo_r2_windage_scale","Rear Windage Scale", "float")
	//AddConVarSetting("CRM.holo_r2_offset_scalar","Offset Strength multiplier","float")
	AddConVarSettingSlider("CRM.holo_r2_reticle_style","Front reticle style [0-7]", 0, 7, 1, true)
	AddConVarSettingSlider("CRM.holo_r2_windage_style","Rear windage style [0-7]", 0, 7, 1, true)
	AddModCategory("^fdffb600CQH SIGHT^e0e0e000 [WINGMAN;WINGMAN_E;MOZAMBIQUE]")
	AddConVarSetting("CRM.cqh_base_colorR", "^ff010000Red^e0e0e000 color intensity", "float")
	AddConVarSetting("CRM.cqh_base_colorG", "^00ff0000Green^e0e0e000 color intensity", "float")
	AddConVarSetting("CRM.cqh_base_colorB", "^0000ff00Blue^e0e0e000 color intensity", "float")
	AddConVarSetting("CRM.cqh_reticle_scale","Front Reticle Scale", "float")
	AddConVarSetting("CRM.cqh_windage_scale","Rear Windage Scale", "float")
	//AddConVarSetting("CRM.cqh_offset_scalar","Offset Strength multiplier","float")
	AddConVarSettingSlider("CRM.cqh_reticle_style","Front reticle style [0-7]", 0, 7, 1, true)
	AddConVarSettingSlider("CRM.cqh_windage_style","Rear windage style [0-7]", 0, 7, 1, true)
	AddModCategory("^fdffb600HCOG1^e0e0e000 [Titanfall 1 hcog]")
	AddConVarSetting("CRM.hcog1_base_colorR", "^ff010000Red^e0e0e000 color intensity", "float")
	AddConVarSetting("CRM.hcog1_base_colorG", "^00ff0000Green^e0e0e000 color intensity", "float")
	AddConVarSetting("CRM.hcog1_base_colorB", "^0000ff00Blue^e0e0e000 color intensity", "float")
	AddConVarSetting("CRM.hcog1_reticle_scale","Front Reticle Scale", "float")
	AddConVarSetting("CRM.hcog1_windage_scale","Rear Windage Scale", "float")
	//AddConVarSetting("CRM.hcog1_offset_scalar","Offset Strength multiplier","float")
	AddConVarSettingSlider("CRM.hcog1_reticle_style","Front reticle style [0-7]", 0, 7, 1, true)
	AddConVarSettingSlider("CRM.hcog1_windage_style","Rear windage style [0-7]", 0, 7, 1, true)
	AddModCategory("^fdffb600HCOG_R5^e0e0e000 [Apex Legends x1 hcog]")
	AddConVarSetting("CRM.hcog5_base_colorR", "^ff010000Red^e0e0e000 color intensity", "float")
	AddConVarSetting("CRM.hcog5_base_colorG", "^00ff0000Green^e0e0e000 color intensity", "float")
	AddConVarSetting("CRM.hcog5_base_colorB", "^0000ff00Blue^e0e0e000 color intensity", "float")
	AddConVarSetting("CRM.hcog5_reticle_scale","Front Reticle Scale", "float")
	//AddConVarSetting("CRM.hcog5_offset_scalar","Offset Strength multiplier","float")
	AddConVarSettingSlider("CRM.hcog5_reticle_style","Front reticle style [0-7]", 0, 7, 1, true)
	AddModCategory("^fdffb600IRON SIGHTS^e0e0e000 [ARs]")
	AddConVarSetting("CRM.r201_front_base_colorR", "^f992ad00R201 ^ff010000Red^e0e0e000 color intensity", "float")
	AddConVarSetting("CRM.r201_front_base_colorG", "^f992ad00R201 ^00ff0000Green^e0e0e000 color intensity", "float")
	AddConVarSetting("CRM.r201_front_base_colorB", "^f992ad00R201 ^0000ff00Blue^e0e0e000 color intensity", "float")
	AddConVarSetting("CRM.r201_front_reticle_scale","^f992ad00R201^e0e0e000 Front Reticle Scale", "float")
	AddConVarSetting("CRM.r201_front_offset_scalar","^f992ad00R201^e0e0e000 Offset Strength multiplier","float")
	AddConVarSettingSlider("CRM.r201_front_reticle_style","^f992ad00R201^e0e0e000 Front reticle style [0-7]", 0, 7, 1, true)
	AddConVarSetting("CRM.hemlok_front_base_colorR", "^fbbcee00Hemlok ^ff010000Red^e0e0e000 color intensity", "float")
	AddConVarSetting("CRM.hemlok_front_base_colorG", "^fbbcee00Hemlok ^00ff0000Green^e0e0e000 color intensity", "float")
	AddConVarSetting("CRM.hemlok_front_base_colorB", "^fbbcee00Hemlok ^0000ff00Blue^e0e0e000 color intensity", "float")
	AddConVarSetting("CRM.hemlok_front_reticle_scale","^fbbcee00Hemlok^e0e0e000 Front Reticle Scale", "float")
	AddConVarSetting("CRM.hemlok_front_offset_scalar","^fbbcee00Hemlok^e0e0e000 Offset Strength multiplier","float")
	AddConVarSettingSlider("CRM.hemlok_front_reticle_style","^fbbcee00Hemlok^e0e0e000 Front reticle style [0-7]", 0, 7, 1, true)
	AddConVarSetting("CRM.g2_front_base_colorR", "^fab4c800G2A5 ^ff010000Red^e0e0e000 color intensity", "float")
	AddConVarSetting("CRM.g2_front_base_colorG", "^fab4c800G2A5 ^00ff0000Green^e0e0e000 color intensity", "float")
	AddConVarSetting("CRM.g2_front_base_colorB", "^fab4c800G2A5 ^0000ff00Blue^e0e0e000 color intensity", "float")
	AddConVarSetting("CRM.g2_front_reticle_scale","^fab4c800G2A5^e0e0e000 Front Reticle Scale", "float")
	AddConVarSetting("CRM.g2_front_offset_scalar","^fab4c800G2A5^e0e0e000 Offset Strength multiplier","float")
	AddConVarSettingSlider("CRM.g2_front_reticle_style","^fab4c800G2A5^e0e0e000 Front reticle style [0-7]", 0, 7, 1, true)
	AddConVarSetting("CRM.vinson_front_base_colorR", "^f78ecf00Flatline ^ff010000Red^e0e0e000 color intensity", "float")
	AddConVarSetting("CRM.vinson_front_base_colorG", "^f78ecf00Flatline ^00ff0000Green^e0e0e000 color intensity", "float")
	AddConVarSetting("CRM.vinson_front_base_colorB", "^f78ecf00Flatline ^0000ff00Blue^e0e0e000 color intensity", "float")
	AddConVarSetting("CRM.vinson_front_reticle_scale","^f78ecf00Flatline^e0e0e000 Front Reticle Scale", "float")
	AddConVarSetting("CRM.vinson_front_offset_scalar","^f78ecf00Flatline^e0e0e000 Offset Strength multiplier","float")
	AddConVarSettingSlider("CRM.vinson_front_reticle_style","^f78ecf00Flatline^e0e0e000 Front reticle style [0-7]", 0, 7, 1, true)
	AddModCategory("^fdffb600IRON SIGHTS^e0e0e000 [SMGs]")
	AddConVarSetting("CRM.car_front_base_colorR", "^cfb9f700CAR SMG ^ff010000Red^e0e0e000 color intensity", "float")
	AddConVarSetting("CRM.car_front_base_colorG", "^cfb9f700CAR SMG ^00ff0000Green^e0e0e000 color intensity", "float")
	AddConVarSetting("CRM.car_front_base_colorB", "^cfb9f700CAR SMG ^0000ff00Blue^e0e0e000 color intensity", "float")
	AddConVarSetting("CRM.car_front_reticle_scale","^cfb9f700CAR SMG^e0e0e000 Front Reticle Scale", "float")
	AddConVarSetting("CRM.car_front_offset_scalar","^cfb9f700CAR SMG^e0e0e000 Offset Strength multiplier","float")
	AddConVarSettingSlider("CRM.car_front_reticle_style","^cfb9f700CAR SMG^e0e0e000 Front reticle style [0-7]", 0, 7, 1, true)
	AddConVarSetting("CRM.alternator_front_base_colorR", "^a480f200Alternator ^ff010000Red^e0e0e000 color intensity", "float")
	AddConVarSetting("CRM.alternator_front_base_colorG", "^a480f200Alternator ^00ff0000Green^e0e0e000 color intensity", "float")
	AddConVarSetting("CRM.alternator_front_base_colorB", "^a480f200Alternator ^0000ff00Blue^e0e0e000 color intensity", "float")
	AddConVarSetting("CRM.alternator_front_reticle_scale","^a480f200Alternator^e0e0e000 Front Reticle Scale", "float")
	AddConVarSetting("CRM.alternator_front_offset_scalar","^a480f200Alternator^e0e0e000 Offset Strength multiplier","float")
	AddConVarSettingSlider("CRM.alternator_front_reticle_style","^a480f200Alternator^e0e0e000 Front reticle style [0-7]", 0, 7, 1, true)
	AddConVarSetting("CRM.r97_front_base_colorR", "^e0cefd00R97 ^ff010000Red^e0e0e000 color intensity", "float")
	AddConVarSetting("CRM.r97_front_base_colorG", "^e0cefd00R97 ^00ff0000Green^e0e0e000 color intensity", "float")
	AddConVarSetting("CRM.r97_front_base_colorB", "^e0cefd00R97 ^0000ff00Blue^e0e0e000 color intensity", "float")
	AddConVarSetting("CRM.r97_front_reticle_scale","^e0cefd00R97^e0e0e000 Front Reticle Scale", "float")
	AddConVarSetting("CRM.r97_front_offset_scalar","^e0cefd00R97^e0e0e000 Offset Strength multiplier","float")
	AddConVarSettingSlider("CRM.r97_front_reticle_style","^e0cefd00R97^e0e0e000 Front reticle style [0-7]", 0, 7, 1, true)
	AddConVarSetting("CRM.hemlok_smg_front_base_colorR", "^c580ed00Volt ^ff010000Red^e0e0e000 color intensity", "float")
	AddConVarSetting("CRM.hemlok_smg_front_base_colorG", "^c580ed00Volt ^00ff0000Green^e0e0e000 color intensity", "float")
	AddConVarSetting("CRM.hemlok_smg_front_base_colorB", "^c580ed00Volt ^0000ff00Blue^e0e0e000 color intensity", "float")
	AddConVarSetting("CRM.hemlok_smg_front_reticle_scale","^c580ed00Volt^e0e0e000 Front Reticle Scale", "float")
	AddConVarSetting("CRM.hemlok_smg_front_offset_scalar","^c580ed00Volt^e0e0e000 Offset Strength multiplier","float")
	AddConVarSettingSlider("CRM.hemlok_smg_front_reticle_style","^c580ed00Volt^e0e0e000 Front reticle style [0-7]", 0, 7, 1, true)
	AddModCategory("^fdffb600IRON SIGHTS^e0e0e000 [LMGs]")
	AddConVarSetting("CRM.hemlok_br_front_base_colorR", "^84ffc900Devotion ^ff010000Red^e0e0e000 color intensity", "float")
	AddConVarSetting("CRM.hemlok_br_front_base_colorG", "^84ffc900Devotion ^00ff0000Green^e0e0e000 color intensity", "float")
	AddConVarSetting("CRM.hemlok_br_front_base_colorB", "^84ffc900Devotion ^0000ff00Blue^e0e0e000 color intensity", "float")
	AddConVarSetting("CRM.hemlok_br_front_reticle_scale","^84ffc900Devotion^e0e0e000 Reticle Scale", "float")
	AddConVarSetting("CRM.hemlok_br_front_offset_scalar","^84ffc900Devotion^e0e0e000 Offset Strength multiplier","float")
	AddConVarSettingSlider("CRM.hemlok_br_front_reticle_style","^84ffc900Devotion^e0e0e000 reticle style [0-7]", 0, 7, 1, true)
	AddConVarSetting("CRM.lstar_front_base_colorR", "^6c8dfa00LSTAR ^ff010000Red^e0e0e000 color intensity", "float")
	AddConVarSetting("CRM.lstar_front_base_colorG", "^6c8dfa00LSTAR ^00ff0000Green^e0e0e000 color intensity", "float")
	AddConVarSetting("CRM.lstar_front_base_colorB", "^6c8dfa00LSTAR ^0000ff00Blue^e0e0e000 color intensity", "float")
	AddConVarSetting("CRM.lstar_front_reticle_scale","^6c8dfa00LSTAR^e0e0e000 Reticle Scale", "float")
	AddConVarSetting("CRM.lstar_front_offset_scalar","^6c8dfa00LSTAR^e0e0e000 Offset Strength multiplier","float")
	AddConVarSettingSlider("CRM.lstar_front_reticle_style","^6c8dfa00LSTAR^e0e0e000 reticle style [0-7]", 0, 7, 1, true)
	AddConVarSetting("CRM.hemlok_lmg_front_base_colorR", "^63dfe400Spitfire ^ff010000Red^e0e0e000 color intensity", "float")
	AddConVarSetting("CRM.hemlok_lmg_front_base_colorG", "^63dfe400Spitfire ^00ff0000Green^e0e0e000 color intensity", "float")
	AddConVarSetting("CRM.hemlok_lmg_front_base_colorB", "^63dfe400Spitfire ^0000ff00Blue^e0e0e000 color intensity", "float")
	AddConVarSetting("CRM.hemlok_lmg_front_reticle_scale","^63dfe400Spitfire^e0e0e000 Reticle Scale", "float")
	AddConVarSetting("CRM.hemlok_lmg_front_offset_scalar","^63dfe400Spitfire^e0e0e000 Offset Strength multiplier","float")
	AddConVarSettingSlider("CRM.hemlok_lmg_front_reticle_style","^63dfe400Spitfire^e0e0e000 reticle style [0-7]", 0, 7, 1, true)
	AddModCategory("^fdffb600IRON SIGHTS^e0e0e000 [SNIPERs]")
	AddConVarSetting("CRM.doubletake_front_base_colorR", "D2 Doubletake ^ff010000Red^e0e0e000 color intensity", "float")
	AddConVarSetting("CRM.doubletake_front_base_colorG", "D2 Doubletake ^00ff0000Green^e0e0e000 color intensity", "float")
	AddConVarSetting("CRM.doubletake_front_base_colorB", "D2 Doubletake ^0000ff00Blue^e0e0e000 color intensity", "float")
	AddConVarSetting("CRM.doubletake_front_reticle_scale","D2 Doubletake Reticle Scale", "float")
	AddConVarSetting("CRM.doubletake_front_offset_scalar","D2 Doubletake Offset Strength multiplier","float")
	AddConVarSettingSlider("CRM.doubletake_front_reticle_style","D2 Doubletake reticle style [0-7]", 0, 7, 1, true)
	AddModCategory("^fdffb600IRON SIGHTS^e0e0e000 [SHOTGUNs]")
	AddConVarSetting("CRM.mastiff_front_base_colorR", "Mastiff ^ff010000Red^e0e0e000 color intensity", "float")
	AddConVarSetting("CRM.mastiff_front_base_colorG", "Mastiff ^00ff0000Green^e0e0e000 color intensity", "float")
	AddConVarSetting("CRM.mastiff_front_base_colorB", "Mastiff ^0000ff00Blue^e0e0e000 color intensity", "float")
	AddConVarSetting("CRM.mastiff_front_reticle_scale","Mastiff Reticle Scale", "float")
	AddConVarSetting("CRM.mastiff_front_offset_scalar","Mastiff Offset Strength multiplier","float")
	AddConVarSettingSlider("CRM.mastiff_front_reticle_style","Mastiff reticle style [0-7]", 0, 7, 1, true)
//	AddModCategory("IRON SIGHTS [PISTOLs]")
//	AddConVarSetting("CRM.autopistol_front_base_colorR", "RE-45 AUTO ^ff010000Red^e0e0e000 color intensity", "float")
//	AddConVarSetting("CRM.autopistol_front_base_colorG", "RE-45 AUTO ^00ff0000Green^e0e0e000 color intensity", "float")
//	AddConVarSetting("CRM.autopistol_front_base_colorB", "RE-45 AUTO ^0000ff00Blue^e0e0e000 color intensity", "float")
//	AddConVarSetting("CRM.autopistol_front_reticle_scale","RE-45 AUTO Reticle Scale", "float")
//	AddConVarSetting("CRM.autopistol_front_offset_scalar","RE-45 AUTO Offset Strength multiplier","float")
//	AddConVarSettingSlider("CRM.autopistol_front_reticle_style","RE-45 AUTO reticle style [0-7]", 0, 7, 1, true)
//	AddConVarSetting("CRM.wingman_front_base_colorR", "Wingman ^ff010000Red^e0e0e000 color intensity", "float")
//	AddConVarSetting("CRM.wingman_front_base_colorG", "Wingman ^00ff0000Green^e0e0e000 color intensity", "float")
//	AddConVarSetting("CRM.wingman_front_base_colorB", "Wingman ^0000ff00Blue^e0e0e000 color intensity", "float")
//	AddConVarSetting("CRM.wingman_front_reticle_scale","Wingman Reticle Scale", "float")
//	AddConVarSetting("CRM.wingman_front_offset_scalar","Wingman Offset Strength multiplier","float")
//	AddConVarSettingSlider("CRM.wingman_front_reticle_style","Wingman reticle style [0-7]", 0, 7, 1, true)
//	AddConVarSetting("CRM.wingman_n_front_base_colorR", "Wingman Elite ^ff010000Red^e0e0e000 color intensity", "float")
//	AddConVarSetting("CRM.wingman_n_front_base_colorG", "Wingman Elite ^00ff0000Green^e0e0e000 color intensity", "float")
//	AddConVarSetting("CRM.wingman_n_front_base_colorB", "Wingman Elite ^0000ff00Blue^e0e0e000 color intensity", "float")
//	AddConVarSetting("CRM.wingman_n_front_reticle_scale","Wingman Elite Reticle Scale", "float")
//	AddConVarSetting("CRM.wingman_n_front_offset_scalar","Wingman Elite Offset Strength multiplier","float")
//	AddConVarSettingSlider("CRM.wingman_n_front_reticle_style","Wingman Elite reticle style [0-7]", 0, 7, 1, true)
//	AddConVarSetting("CRM.mozambique_front_base_colorR", "Mozambique ^ff010000Red^e0e0e000 color intensity", "float")
//	AddConVarSetting("CRM.mozambique_front_base_colorG", "Mozambique ^00ff0000Green^e0e0e000 color intensity", "float")
//	AddConVarSetting("CRM.mozambique_front_base_colorB", "Mozambique ^0000ff00Blue^e0e0e000 color intensity", "float")
//	AddConVarSetting("CRM.mozambique_front_reticle_scale","Mozambique Reticle Scale", "float")
//	AddConVarSetting("CRM.mozambique_front_offset_scalar","Mozambique Offset Strength multiplier","float")
//	AddConVarSettingSlider("CRM.mozambique_front_reticle_style","Mozambique reticle style [0-7]", 0, 7, 1, true)
}