global function CRMframeworkAddSetings

void function CRMframeworkAddSetings(){
	AddModTitle("Custom Reticle Mod - ui Framework")
	AddModCategory("Universal Scopes")
	
	AddConVarSettingEnum("CRM.rgb_override", "RGB mode", ["Off", "On"])
	AddModCategory("AOG_R1 @35fov [R101]")
	AddConVarSetting("CRM.aog_r1_base_colorR", "red color intensity", "float")
	AddConVarSetting("CRM.aog_r1_base_colorG", "green color intensity", "float")
	AddConVarSetting("CRM.aog_r1_base_colorB", "blue color intensity", "float")
	AddConVarSetting("CRM.aog_r1_reticle_scale","Front Reticle Scale", "float")
	AddConVarSetting("CRM.aog_r1_offset_scalarX","Offset Strength multiplier [X]","float")
	AddConVarSetting("CRM.aog_r1_offset_scalarY", "Offset Strength multiplier [Y]", "float")
	AddConVarSettingSlider("CRM.aog_r1_reticle_style","Front reticle style [0-7]", 0, 7, 1, true)
	AddModCategory("HCOG2 @35fov [R201;R101;HEMLOK;G2;V-47;ALTERNATOR]")
	AddConVarSetting("CRM.hcog2_base_colorR", "red color intensity", "float")
	AddConVarSetting("CRM.hcog2_base_colorG", "green color intensity", "float")
	AddConVarSetting("CRM.hcog2_base_colorB", "blue color intensity", "float")
	AddConVarSetting("CRM.hcog2_reticle_scale","Front Reticle Scale", "float")
	AddConVarSetting("CRM.hcog2_offset_scalarX","Offset Strength multiplier [X]","float")
	AddConVarSetting("CRM.hcog2_offset_scalarY", "Offset Strength multiplier [Y]", "float")
	AddConVarSettingSlider("CRM.hcog2_reticle_style","Front reticle style [0-7]", 0, 7, 1, true)
	AddModCategory("ACGS @25fov [UNIVERSAL]")
	AddConVarSetting("CRM.acgs_base_colorR", "red color intensity", "float")
	AddConVarSetting("CRM.acgs_base_colorG", "green color intensity", "float")
	AddConVarSetting("CRM.acgs_base_colorB", "blue color intensity", "float")
	AddConVarSetting("CRM.acgs_reticle_scale","Front Reticle Scale", "float")
	AddConVarSetting("CRM.acgs_offset_scalarX","Offset Strength multiplier [X]","float")
	AddConVarSetting("CRM.acgs_offset_scalarY", "Offset Strength multiplier [Y]", "float")
	AddConVarSettingSlider("CRM.acgs_reticle_style","Front reticle style [0-7]", 0, 7, 1, true)
	AddModCategory("AOG_R2 @20fov [SPITFIRE;LSTAR;DEVOTION]")
	AddConVarSetting("CRM.aog_r2_base_colorR", "red color intensity", "float")
	AddConVarSetting("CRM.aog_r2_base_colorG", "green color intensity", "float")
	AddConVarSetting("CRM.aog_r2_base_colorB", "blue color intensity", "float")
	AddConVarSetting("CRM.aog_r2_reticle_scale","Front Reticle Scale", "float")
	AddConVarSetting("CRM.aog_r2_offset_scalarX","Offset Strength multiplier [X]","float")
	AddConVarSetting("CRM.aog_r2_offset_scalarY", "Offset Strength multiplier [Y]", "float")
	AddConVarSettingSlider("CRM.aog_r2_reticle_style","Front reticle style [0-7]", 0, 7, 1, true)
	AddModCategory("THREAT_SCOPE @35fov [R201;R101;HEMLOK;G2;V-47;SPITFIRE;LSTAR;DEVOTION]")
	AddConVarSetting("CRM.cro_base_colorR", "red color intensity", "float")
	AddConVarSetting("CRM.cro_base_colorG", "green color intensity", "float")
	AddConVarSetting("CRM.cro_base_colorB", "blue color intensity", "float")
	AddConVarSetting("CRM.cro_reticle_scale","Front Reticle Scale", "float")
	AddConVarSetting("CRM.cro_offset_scalarX","Offset Strength multiplier [X]","float")
	AddConVarSetting("CRM.cro_offset_scalarY", "Offset Strength multiplier [Y]", "float")
	AddConVarSettingSlider("CRM.cro_reticle_style","Front reticle style [0-7]", 0, 7, 1, true)
	AddModCategory("HOLO_R2 @45fov [CAR;VOLT;R97]")
	AddConVarSetting("CRM.holo_r2_base_colorR", "red color intensit", "float")
	AddConVarSetting("CRM.holo_r2_base_colorG", "green color intensit", "float")
	AddConVarSetting("CRM.holo_r2_base_colorB", "blue color intensit", "float")
	AddConVarSetting("CRM.holo_r2_reticle_scale","Front Reticle Scal", "float")
	AddConVarSetting("CRM.holo_r2_offset_scalarX","Offset Strength multiplie [X]","float")
	AddConVarSetting("CRM.holo_r2_offset_scalarY", "Offset Strength multiplie [Y]", "float")
	AddConVarSettingSlider("CRM.holo_r2_reticle_style","Front reticle styl [0-7]", 0, 7, 1, true)
}